ALGORITHM: DDQN

NUM_EPISODES: 100
MAX_MEMORY_SIZE: 500_000
BATCH_SIZE: 64
TARGET_NETWORK_RESET: 100

NETWORK_CONFIG:
    hidden_layers: [512, 512]
    optimizer: Adam
    lr: 0.0001
    lr_scheduler:
        scheduler: LinearLR
        kwargs:
            start_factor: 1
            end_factor: 0.1
            total_iters: 40

EXPLORATION_STRATEGY:
      name: epsilon_greedy
      max_value: 1
      min_value: 0.005
      num_episodes: 40
