ALGORITHM: IAC_PS

NUM_EPISODES: 100_000
MAX_MEMORY_SIZE: 10_000
BATCH_SIZE: 64
DISCOUNT_FACTOR: 0.99

ACTOR_CONFIG:
    hidden_layers: [32, 32]
    optimizer: Adam
    lr: 0.0005
    lr_scheduler:
        scheduler: LinearLR
        kwargs:
            start_factor: 1
            end_factor: 0.1
            total_iters: 10_000

CRITIC_CONFIG:
    hidden_layers: [64, 64]
    optimizer: Adam
    lr: 0.001
    lr_scheduler:
        scheduler: LinearLR
        kwargs:
            start_factor: 1
            end_factor: 0.1
            total_iters: 25_000

EXPLORATION_STRATEGY:
      name: epsilon_greedy
      max_value: 1
      min_value: 0.005
      num_episodes: 10_000
      